import { createContext, useContext, useState, useEffect } from 'react'

const dictionary = {
  en: {
    'lang.switch': 'मराठी',
    'app.title': 'GeoPresence',
    'role.supervisor': 'Supervisor',
    'role.employee': 'Employee',
    'common.ward': 'Ward',
    
    'nav.home': 'Home',
    'nav.tasks': 'Tasks',
    'nav.attendance': 'Attendance',
    'nav.map': 'Map',
    'nav.history': 'History',
    'nav.logout': 'Logout',

    'tasks.title': 'Tasks',
    'tasks.assign_new': 'Assign a new task',
    'tasks.task_title': 'Task Title',
    'tasks.task_title_ph': 'e.g. Road Cleaning',
    'tasks.description': 'Description',
    'tasks.description_ph': 'e.g. Clean Market Area',
    'tasks.assign_employee': 'Assign Employee',
    'tasks.status': 'Status',
    'tasks.create': 'Create Task',
    'tasks.select': 'Select…',
    'tasks.all_employees': 'All Employees',
    'tasks.all_tasks': 'All Tasks',
    'tasks.all': 'All',
    'tasks.pending': 'Pending',
    'tasks.in_progress': 'In Progress',
    'tasks.completed': 'Completed',
    'tasks.no_tasks': 'No tasks here.',
    'tasks.no_employees': 'No employees in your ward yet.',
    'tasks.assigned_to': 'Assigned to',
    'tasks.geo_opt': 'Geofence Location (Optional)',
    'tasks.geo_desc': 'Require the employee to be at this location to check in.',
    'tasks.loc_name': 'Location Name',
    'tasks.loc_name_ph': 'e.g. Ram Mandir Chowk',
    'tasks.use_loc': '📍 Use My Location',
    'tasks.loc_selected': 'Location selected.',
    'tasks.post_photo': 'Post Work Photo',
    'tasks.work_photos': 'Work Photos',
    'tasks.add_photo_title': 'Upload Work Photo',
    'tasks.photo_caption': 'Description / Note (Optional)',
    'tasks.photo_caption_ph': 'e.g., Cleaned section near chowk',
    'tasks.upload_btn': 'Upload Photo',
    'tasks.photos_count': 'Photos',
    'tasks.view_photo': 'View Photo',
    'tasks.no_photos': 'No work photos uploaded yet',

    'auth.login': 'Log In',
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.no_account': 'Don\'t have an account? Register',
    'auth.demo_sup': 'Demo Supervisor',
    'auth.demo_emp': 'Demo Employee',
    'auth.register': 'Create Account',
    'auth.name': 'Full Name',
    'auth.role': 'Role',
    'auth.have_account': 'Already have an account? Log in',
    'auth.loading': 'Loading...',

    'sup_dash.total_emp': 'Total Employees',
    'sup_dash.present': 'Present Today',
    'sup_dash.absent': 'Absent Today',
    'sup_dash.tasks_assigned': 'Tasks Assigned',
    'sup_dash.tasks_completed': 'tasks completed',
    'sup_dash.employees': 'Employees',
    'sup_dash.view_att': 'View attendance',
    'sup_dash.task_assigned': 'tasks assigned',
    'sup_dash.open': 'open',
    'sup_dash.in': 'In',
    'sup_dash.present_badge': 'Present',
    'sup_dash.out_badge': 'Checked Out',
    'sup_dash.absent_badge': 'Absent',
    'sup_dash.no_emp': 'No employees have registered for Ward',
    'sup_dash.assign_btn': 'Assign Task',
    'sup_dash.map_btn': 'Live Map',

    'sup_att.title': 'Today\'s Attendance',
    'sup_att.date': 'Date',
    'sup_att.check_in': 'Check In',
    'sup_att.check_out': 'Check Out',
    'sup_att.location': 'Location',
    'sup_att.not_yet': 'Not yet',
    'sup_att.no_checkin': 'No check in on this date.',

    'sup_map.title': 'Live Map',
    'sup_map.subtitle': 'Showing employee check-in locations for today',
    'sup_map.no_data': 'No employee locations recorded today.',
    'sup_map.checked_in_at': 'Checked in at',

    'emp_dash.welcome': 'Welcome',
    'emp_dash.ward_num': 'Ward Number',
    'emp_dash.supervisor': 'Your Supervisor',
    'emp_dash.not_assigned': 'Not assigned yet',
    'emp_dash.no_sup_note': 'A supervisor for this ward has not registered yet.',
    'emp_dash.mark_att': 'Mark Attendance',
    'emp_dash.not_checked_in': 'You have not checked in today',
    'emp_dash.checked_in_at': 'Checked in at',
    'emp_dash.checked_out_at': 'Checked out at',
    'emp_dash.check_in_btn': 'CHECK IN',
    'emp_dash.check_out_btn': 'CHECK OUT',
    'emp_dash.att_note': 'A selfie and your GPS location are recorded with every check in / out.',
    'emp_dash.assigned_tasks': 'Assigned Tasks',
    'emp_dash.open_tasks': 'open',
    'emp_dash.start_work': 'Start Work',
    'emp_dash.mark_completed': 'Mark Completed',
    'emp_dash.checkin_first': 'You must check in first to start this task.',
    'emp_dash.no_tasks': 'No tasks assigned yet. Your supervisor will assign work here.',

    'emp_hist.title': 'Attendance History',
    'emp_hist.date': 'Date',
    'emp_hist.time': 'Time',
    'emp_hist.type': 'Type',
    'emp_hist.status': 'Status',
    'emp_hist.loc': 'Location',
    'emp_hist.no_hist': 'No attendance records found.',

    'cap.check_in': 'Check In',
    'cap.check_out': 'Check Out',
    'cap.close': 'Close',
    'cap.cancel': 'Cancel',
    'cap.success': 'Attendance Recorded Successfully',
    'cap.saved_msg': 'saved with your photo and location.',
    'cap.done': 'Done',
    'cap.saving': 'Saving attendance…',
    'cap.loc_ready': 'Location ready',
    'cap.loc_loading': 'Getting your location…',
    'cap.loc_error': 'Location not available. Allow location access.',
    'cap.retry': 'Retry',
    'cap.take_selfie': 'Take Selfie',
    'cap.open_cam': 'Open Phone Camera',
    'cap.use_app': 'Use phone camera app instead',
    'cap.retake': 'Retake',
    'cap.confirm': 'Confirm',
    'cap.liveness_prompt': 'Please blink your eyes once to verify liveness',
    'cap.liveness_verified': 'Liveness verified! Blink detected',
    'cap.liveness_title': 'Liveness Verification',
    'cap.blink_btn': 'I Blinked',
  },
  mr: {
    'lang.switch': 'English',
    'app.title': 'जिओ प्रेझेंस (GeoPresence)',
    'role.supervisor': 'पर्यवेक्षक (Supervisor)',
    'role.employee': 'कर्मचारी (Employee)',
    'common.ward': 'वॉर्ड',
    
    'nav.home': 'मुखपृष्ठ',
    'nav.tasks': 'कामे',
    'nav.attendance': 'उपस्थिती',
    'nav.map': 'नकाशा',
    'nav.history': 'इतिहास',
    'nav.logout': 'बाहेर पडा',

    'tasks.title': 'कामे',
    'tasks.assign_new': 'नवीन काम द्या',
    'tasks.task_title': 'कामाचे नाव',
    'tasks.task_title_ph': 'उदा. रस्ता साफ करणे',
    'tasks.description': 'वर्णन',
    'tasks.description_ph': 'उदा. मार्केट परिसर साफ करा',
    'tasks.assign_employee': 'कर्मचारी निवडा',
    'tasks.status': 'स्थिती',
    'tasks.create': 'काम तयार करा',
    'tasks.select': 'निवडा…',
    'tasks.all_employees': 'सर्व कर्मचारी',
    'tasks.all_tasks': 'सर्व कामे',
    'tasks.all': 'सर्व',
    'tasks.pending': 'प्रलंबित',
    'tasks.in_progress': 'सुरू आहे',
    'tasks.completed': 'पूर्ण झाले',
    'tasks.no_tasks': 'येथे कोणतीही कामे नाहीत.',
    'tasks.no_employees': 'तुमच्या वॉर्डमध्ये अद्याप कोणतेही कर्मचारी नाहीत.',
    'tasks.assigned_to': 'कर्मचारी:',
    'tasks.geo_opt': 'जिओफेन्स लोकेशन (पर्यायी)',
    'tasks.geo_desc': 'चेक-इन करण्यासाठी कर्मचाऱ्याला या ठिकाणी असणे आवश्यक करा.',
    'tasks.loc_name': 'ठिकाणाचे नाव',
    'tasks.loc_name_ph': 'उदा. राम मंदिर चौक',
    'tasks.use_loc': '📍 माझे लोकेशन वापरा',
    'tasks.loc_selected': 'लोकेशन निवडले.',
    'tasks.post_photo': 'कामाचा फोटो पोस्ट करा',
    'tasks.work_photos': 'कामाचे फोटो',
    'tasks.add_photo_title': 'कामाचा फोटो अपलोड करा',
    'tasks.photo_caption': 'नोंद / वर्णन (पर्यायी)',
    'tasks.photo_caption_ph': 'उदा. चौकाजवळील रस्ता स्वच्छ केला',
    'tasks.upload_btn': 'फोटो अपलोड करा',
    'tasks.photos_count': 'फोटो',
    'tasks.view_photo': 'फोटो पहा',
    'tasks.no_photos': 'अद्याप कोणतेही कामाचे फोटो नाहीत',

    'auth.login': 'लॉगिन करा',
    'auth.email': 'ईमेल',
    'auth.password': 'पासवर्ड',
    'auth.no_account': 'खाते नाही? नोंदणी करा',
    'auth.demo_sup': 'डेमो पर्यवेक्षक',
    'auth.demo_emp': 'डेमो कर्मचारी',
    'auth.register': 'खाते तयार करा',
    'auth.name': 'पूर्ण नाव',
    'auth.role': 'भूमिका',
    'auth.have_account': 'आधीच खाते आहे? लॉगिन करा',
    'auth.loading': 'लोड होत आहे...',

    'sup_dash.total_emp': 'एकूण कर्मचारी',
    'sup_dash.present': 'आज उपस्थित',
    'sup_dash.absent': 'आज अनुपस्थित',
    'sup_dash.tasks_assigned': 'दिलेली कामे',
    'sup_dash.tasks_completed': 'कामे पूर्ण झाली',
    'sup_dash.employees': 'कर्मचारी',
    'sup_dash.view_att': 'उपस्थिती पहा',
    'sup_dash.task_assigned': 'कामे दिली',
    'sup_dash.open': 'प्रलंबित',
    'sup_dash.in': 'आत',
    'sup_dash.present_badge': 'उपस्थित',
    'sup_dash.out_badge': 'बाहेर (चेक आऊट)',
    'sup_dash.absent_badge': 'अनुपस्थित',
    'sup_dash.no_emp': 'या वॉर्डसाठी अद्याप कोणीही कर्मचारी नोंदणीकृत नाही.',
    'sup_dash.assign_btn': 'काम द्या',
    'sup_dash.map_btn': 'नकाशा पहा',

    'sup_att.title': 'आजची उपस्थिती',
    'sup_att.date': 'दिनांक',
    'sup_att.check_in': 'चेक इन',
    'sup_att.check_out': 'चेक आऊट',
    'sup_att.location': 'ठिकाण',
    'sup_att.not_yet': 'अद्याप नाही',
    'sup_att.no_checkin': 'आजचे कोणतेही चेक-इन नाही.',

    'sup_map.title': 'लाईव्ह नकाशा',
    'sup_map.subtitle': 'आजचे कर्मचाऱ्यांचे चेक-इन लोकेशन दाखवत आहे',
    'sup_map.no_data': 'आज कोणाचेही लोकेशन नोंदवले गेले नाही.',
    'sup_map.checked_in_at': 'चेक इन केले:',

    'emp_dash.welcome': 'स्वागत आहे',
    'emp_dash.ward_num': 'वॉर्ड क्र.',
    'emp_dash.supervisor': 'तुमचे पर्यवेक्षक',
    'emp_dash.not_assigned': 'अद्याप दिलेले नाही',
    'emp_dash.no_sup_note': 'या वॉर्डसाठी पर्यवेक्षकाने अद्याप नोंदणी केलेली नाही.',
    'emp_dash.mark_att': 'उपस्थिती नोंदवा',
    'emp_dash.not_checked_in': 'तुम्ही आज चेक इन केलेले नाही',
    'emp_dash.checked_in_at': 'चेक इन केले:',
    'emp_dash.checked_out_at': 'चेक आऊट केले:',
    'emp_dash.check_in_btn': 'चेक इन',
    'emp_dash.check_out_btn': 'चेक आऊट',
    'emp_dash.att_note': 'तुमचा सेल्फी आणि GPS लोकेशन प्रत्येक चेक-इन/आऊट वेळी सेव्ह केले जाते.',
    'emp_dash.assigned_tasks': 'दिलेली कामे',
    'emp_dash.open_tasks': 'प्रलंबित',
    'emp_dash.start_work': 'काम सुरू करा',
    'emp_dash.mark_completed': 'काम पूर्ण झाले',
    'emp_dash.checkin_first': 'हे काम सुरू करण्यासाठी प्रथम चेक-इन करा.',
    'emp_dash.no_tasks': 'कोणतेही काम दिलेले नाही. तुमचे पर्यवेक्षक येथे कामे देतील.',

    'emp_hist.title': 'उपस्थिती इतिहास',
    'emp_hist.date': 'दिनांक',
    'emp_hist.time': 'वेळ',
    'emp_hist.type': 'प्रकार',
    'emp_hist.status': 'स्थिती',
    'emp_hist.loc': 'ठिकाण',
    'emp_hist.no_hist': 'कोणताही उपस्थिती इतिहास सापडला नाही.',

    'cap.check_in': 'चेक इन',
    'cap.check_out': 'चेक आऊट',
    'cap.close': 'बंद करा',
    'cap.cancel': 'रद्द करा',
    'cap.success': 'उपस्थिती यशस्वीरित्या नोंदवली गेली',
    'cap.saved_msg': 'तुमचा फोटो आणि लोकेशनसह सेव्ह केले.',
    'cap.done': 'पूर्ण झाले',
    'cap.saving': 'सेव्ह करत आहे…',
    'cap.loc_ready': 'लोकेशन तयार आहे',
    'cap.loc_loading': 'लोकेशन मिळवत आहे…',
    'cap.loc_error': 'लोकेशन मिळत नाही. कृपया लोकेशन अक्सेस चालू करा.',
    'cap.retry': 'पुन्हा प्रयत्न करा',
    'cap.take_selfie': 'सेल्फी घ्या',
    'cap.open_cam': 'कॅमेरा उघडा',
    'cap.use_app': 'त्याऐवजी फोनचा कॅमेरा अ‍ॅप वापरा',
    'cap.retake': 'पुन्हा घ्या',
    'cap.confirm': 'नक्की करा',
    'cap.liveness_prompt': 'कृपया सजीवतेची पडताळणी करण्यासाठी एकदा डोळे मिचकावा',
    'cap.liveness_verified': 'पडताळणी यशस्वी! डोळे मिचकावणे नोंदवले',
    'cap.liveness_title': 'सजीवता पडताळणी (Liveness Check)',
    'cap.blink_btn': 'डोळे मिचकावले',
  }
}

const LanguageContext = createContext()

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(localStorage.getItem('gp_lang') || 'en')

  useEffect(() => {
    localStorage.setItem('gp_lang', lang)
  }, [lang])

  const t = (key) => dictionary[lang][key] || key

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => useContext(LanguageContext)
